/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo Umul
 */
public class AgendaContactosBD extends javax.swing.JFrame {
   conexionMysql conec = new conexionMysql(); //llamado de clase
   Connection conectar = conec.getConnection(); // llamado de conexion

    /**
     * Creates new form BaseProductosSuperDelBarrio
     */
    public AgendaContactosBD() {
        initComponents();
        Consultar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(51, 51, 255)));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Telefono", "Dirección", "Curso"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(153, 255, 255));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 760, 210));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setText("ID Contacto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 200, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("Nombres del contacto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos del contacto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 120, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel5.setText("Curso:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 50, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/Tabla.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 140, 130));

        jLabel9.setBackground(new java.awt.Color(153, 153, 255));
        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel9.setText("Dirección:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 80, 20));

        btnNuevo.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.setLabel("Agregar nuevo contacto");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 30));

        btnModificar.setBackground(new java.awt.Color(255, 255, 204));
        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Editar contacto");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 140, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar contacto");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 150, 30));

        btnConsultar.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar estado de agenda");
        btnConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 230, 30));

        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 310, -1));

        txtNombres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 310, -1));

        txtApellidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 310, -1));

        txtNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 310, -1));

        txtDireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 310, -1));

        txtCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 310, -1));

        txtBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 330, 30));

        btnBuscar.setBackground(new java.awt.Color(255, 153, 153));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar contactos");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 160, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/Union.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    Guardar();
        txtCodigo.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtNumero.setText("");
        txtDireccion.setText("");
        txtCurso.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     Borrar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Consultar("");
        txtCodigo.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtNumero.setText("");
        txtDireccion.setText("");
        txtCurso.setText("");
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        GestionDeTabla();    
    }//GEN-LAST:event_TablaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ModificarDatos();
    }//GEN-LAST:event_btnModificarActionPerformed

    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
      String textoBusqueda = txtBuscar.getText();
      Buscar(textoBusqueda); // Llama a la función Consultar con el campo y el texto de búsqueda
    }//GEN-LAST:event_btnBuscarActionPerformed

public void Consultar(String NombreContacto) {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Numero_de_telefono");
    modelo.addColumn("Direccion");
    modelo.addColumn("Curso");
    Tabla.setModel(modelo);
    
    String sql = "";
    if (NombreContacto.equals("")) {
        sql = "SELECT * FROM contactos";
    } else {
        sql = "SELECT * FROM contactos WHERE Nombres LIKE '%" + NombreContacto + "%'";
    }
    
    String agenda[] = new String[6]; // Cambio: Tamaño del arreglo a 6
    Statement set;
    
    try {
        set = conectar.createStatement();
        ResultSet resul = set.executeQuery(sql);
        while (resul.next()) {
            agenda[0] = resul.getString(1);
            agenda[1] = resul.getString(2);
            agenda[2] = resul.getString(3);
            agenda[3] = resul.getString(4);
            agenda[4] = resul.getString(5);
            agenda[5] = resul.getString(6); // Cambio: Acceso a la columna 6
            modelo.addRow(agenda);
        }
        Tabla.setModel(modelo);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "El error es: " + ex);
    }
}

public void Buscar(String textoBusqueda) {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Numero_de_telefono");
    modelo.addColumn("Direccion");
    modelo.addColumn("Curso");
    Tabla.setModel(modelo);

    String sql = "";

    if (textoBusqueda.equals("Nombre")) {
        sql = "SELECT * FROM contactos WHERE Nombres LIKE '%" + textoBusqueda + "%'";
    } else if (textoBusqueda.equals("Apellido")) {
        sql = "SELECT * FROM contactos WHERE Apellidos LIKE '%" + textoBusqueda + "%'";
    } else if (textoBusqueda.equals("Curso")) {
        sql = "SELECT * FROM contactos WHERE Curso LIKE '%" + textoBusqueda + "%'";
    } else {
        // Si no se seleccionó un campo específico, busca en todos los campos
        sql = "SELECT * FROM contactos WHERE " +
              "Nombres LIKE '%" + textoBusqueda + "%' OR " +
              "Apellidos LIKE '%" + textoBusqueda + "%' OR " +
              "Curso LIKE '%" + textoBusqueda + "%'";
    }

    try {
        Statement set = conectar.createStatement();
        ResultSet resul = set.executeQuery(sql);
        while (resul.next()) {
            String[] agenda = new String[6];
            agenda[0] = resul.getString(1);
            agenda[1] = resul.getString(2);
            agenda[2] = resul.getString(3);
            agenda[3] = resul.getString(4);
            agenda[4] = resul.getString(5);
            agenda[5] = resul.getString(6);
            modelo.addRow(agenda);
        }
        Tabla.setModel(modelo);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "El error es: " + ex);
    }
}



 public void Guardar(){
     String ID = txtCodigo.getText();
     String Nombres = txtNombres.getText();
     String Apellidos = txtApellidos.getText();
     String Numero = txtNumero.getText();
     String Direccion =txtDireccion.getText();
     String Curso = txtCurso.getText();
     
     
     String Sql="Insert into contactos() Values(?,?,?,?,?,?)";
    try {
        Statement set= conectar.createStatement();
        ResultSet resultado = set.executeQuery("Select*from contactos where ID like'"+txtCodigo.getText()+"'");
        if(resultado.next()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Usuario ya existe");
            txtCodigo.requestFocus();
        }else if(txtCodigo.getText().isEmpty()){
             getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Identidad Obligatoria");
            txtCodigo.requestFocus();
        }else{
            PreparedStatement pasar =conectar.prepareStatement(Sql);
            pasar.setString(1, ID);
            pasar.setString(2, Nombres);
            pasar.setString(3, Apellidos);
            pasar.setString(4, Numero);
            pasar.setString(5, Direccion);
            pasar.setString(6, Curso);
            pasar.executeUpdate();
            JOptionPane.showMessageDialog(null,"Contacto agregado");
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"El error es:"+ex);
    }
     
 }
 public void GestionDeTabla(){
     int fila=Tabla.getSelectedRow();
     if(fila>=0){
         txtCodigo.setText(Tabla.getValueAt(fila,0).toString());
          txtNombres.setText(Tabla.getValueAt(fila,1).toString());
           txtApellidos.setText(Tabla.getValueAt(fila,2).toString());
            txtNumero.setText(Tabla.getValueAt(fila,3).toString());
             txtDireccion.setText(Tabla.getValueAt(fila,4).toString());
               txtCurso.setText(Tabla.getValueAt(fila,5).toString());
     }else{
         JOptionPane.showMessageDialog(null,"No se selecciono fila");
     }
 }
 public void ModificarDatos(){
    try {
        PreparedStatement pasar = conectar.prepareStatement("Update contactos set Nombres ='"+txtNombres.getText()+"',Apellidos ='"+txtApellidos.getText()+"',Numero_de_telefono='"+txtNumero.getText()
                +"',Direccion='"+txtDireccion.getText()+"',Curso='"+txtCurso.getText()+"' where ID='"+txtCodigo.getText()+"'");
        pasar.executeUpdate();
        Consultar("");
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"El error es:"+ex);
    }
 }
 public void Borrar(){
    int fila=Tabla.getSelectedRow();
    String ID_Contacto =Tabla.getValueAt(fila,0).toString();
    int n=JOptionPane.showConfirmDialog(null,"Desea eliminar de la agenda","Agenda",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    if(n==JOptionPane.YES_NO_OPTION){
    try {
        PreparedStatement borrar=conectar.prepareStatement("Delete from contactos where ID ='"+ID_Contacto+"'");
        borrar.executeUpdate();
        Consultar("");
    } catch (SQLException ex) {
      JOptionPane.showConfirmDialog(null,"Desea eliminar registro"+ex);
    }
    }
}   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaContactosBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaContactosBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaContactosBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaContactosBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaContactosBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
